### ISSUE TITLE
fyne-theme-generator.exe: Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by somera** [lusingander/fyne-theme-generator#8]
I got this finding `Trojan:Win32/Wacatac.B!ml` today after I compile the project on Windows 11 with go 1.21.4

**Comment by lusingander** [comment]
Thank you for bringing this to my attention.

I believe this is a false positive detection by the antivirus software.
Since I do not distribute any binaries and the entire source code is openly available, I would appreciate it if you could exclude it from your own security software based on your judgment.
